In [1]:
#numpy

In [10]:
from numpy import*
import time
def trad_version():
        t1 = time.time()
        X = range(10000000)
        Y = range(10000000)
        Z = []
        for i in range(len(X)):
            Z.append(X[i]+Y[i])
        return time.time()-t1
trad_version()

1.7239739894866943

In [11]:
def numpy_version():
    t1 = time . time ()
    X = arange (10000000)
    Y = arange (10000000)
    Z= X+Y
    return time.time()-t1
numpy_version()

0.03144526481628418

In [12]:
import numpy as np

In [13]:
import warnings
warnings.filterwarnings('ignore')

In [14]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [15]:
type(list1)

list

In [16]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [17]:
arr1.data

In [19]:
type(arr1)

numpy.ndarray

arr1.dtype 

In [20]:
arr1.dtype

dtype('int32')

In [21]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [23]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
np.arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [30]:
a = np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [31]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [33]:
ar1 = np.arange(1,20)
ar1[ar1%2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [35]:
ar1 = np.arange(0,22)
ar1[ar1%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [37]:
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [38]:
#rastgele sayılar

In [39]:
np.random.random(4)

array([0.76865195, 0.0171668 , 0.79337782, 0.5861528 ])

In [40]:
np.random.randint(0,500,5)

array([ 39,  91, 327, 385, 256])

In [41]:
np.random.randint(0,500,10)

array([265, 173, 102, 126,  53,  28, 491, 161, 172,  31])

In [42]:
#seed
np.random.seed(123)
np.random.randint(0,100,10)


array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [43]:
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [45]:
f1 = np.random.uniform(5,10, size = (10))
f1

array([7.65913794, 8.17200479, 9.24715897, 8.62227662, 8.05511755,
       8.61221691, 6.61479457, 6.80894328, 6.14131615, 6.46857023])

In [46]:
#Bu sayıların tam sayı kısmını almak yöntem 1
np.floor(f1)

array([7., 8., 9., 8., 8., 8., 6., 6., 6., 6.])

In [47]:
#Bu sayıların tam sayı kısmını almak yöntem 2
np.trunc(f1)

array([7., 8., 9., 8., 8., 8., 6., 6., 6., 6.])

In [48]:
#Bu sayıların noktalı kısımlarını görmemek için
f1.astype(int)

array([7, 8, 9, 8, 8, 8, 6, 6, 6, 6])

In [49]:
#normal distribution
b2=np.random. randn(10)
b2

array([-0.74856868,  0.24036728, -1.85563747, -1.7794548 , -2.75022426,
       -0.23415755, -0.69598118, -1.77413406,  2.36160126,  0.03499308])

In [50]:
arr1

array([10, 20, 30, 40, 50, 60])

In [51]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [52]:
#Dizi üzerinde yapılabilecek operasyonlar
arr2= np.arange(0,20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
arr2.sum()

190

In [54]:
np.cumsum(arr2)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190])

In [55]:
np.min(arr2)

0

In [56]:
np.max(arr2)

19

In [57]:
#min sayının indeksini veriyor.
np.argmin(arr2)

0

In [58]:
#max sayının indeksini veriyor.
np.argmax(arr2)

19

In [59]:
#ortalama
np.mean(arr2)

9.5

In [60]:
#medyan
np.median(arr2)

9.5

In [61]:
#varyans
np.var(arr2)

33.25

In [62]:
#standart sapma
np.std(arr2)

5.766281297335398

In [64]:
#2D diziler üzerindeki operasyonlar


In [65]:
A = np.array ([[1,2,3,0], [5,6,7,22], [10,11,1,13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [66]:
A.sum()

129

In [67]:
A.max()

22

In [68]:
A.min()

0

In [71]:
#sütundaki minimumlar
np.amin(A, axis = 0)

array([1, 2, 1, 0])

In [72]:
#satırdaki minimumlar
np.amin(A, axis = 1)

array([0, 5, 1, 3])

In [74]:
#satırdaki ortalama
np.mean(A, axis = 1)

array([ 1.5 , 10.  ,  8.75, 12.  ])

In [75]:
#satırdaki medyan
np.median(A, axis = 1)

array([ 1.5,  6.5, 10.5, 14.5])

In [76]:
#satırdaki varyasyon
np.var(A, axis = 1)

array([ 1.25  , 48.5   , 21.1875, 27.5   ])

In [77]:
#satırdaki standart sapma
np.std(A, axis = 1)

array([1.11803399, 6.96419414, 4.60298816, 5.24404424])

In [80]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [81]:
#eleman yer değiştirme
ar = np.arange (1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [82]:
rep1 = np. where(ar %2 ==0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [84]:
ar2 = np. array([10, 20, 30, 10, 10, 20 ,20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [85]:
rep2 = np. where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [86]:
p2 = np. arange(0,100,10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [87]:
np.put(p2, [0,3,5], [33,55,99] )
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])